# Generated by Django 5.0.3 on 2024-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
