# Generated by Django 5.0.3 on 2024-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vendor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
