# Generated by Django 5.0.3 on 2024-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_vendor_cover_image_alter_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='+380 069 412 4100', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='vendor.jpg', upload_to='vendor'),
        ),
    ]
